In [1]:
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
np.array([10.0]*5)

array([10., 10., 10., 10., 10.])

In [10]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [14]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
np.random.uniform(0,5)

1.343744808823966

In [87]:
np.random.rand() * 5

0.18063515497499905

In [32]:
np.random.randn(5,5)

array([[-0.44456508,  1.48670499, -0.15539751,  0.16281126, -0.66378482],
       [ 1.47794789,  0.56324781, -0.19839481,  0.06626626, -0.00368174],
       [ 1.5460204 ,  0.26486139,  1.0308722 ,  0.24313539, -1.11149725],
       [-0.50817267, -0.17792038, -0.31519266, -1.83072971,  0.04000866],
       [ 2.86682221,  1.10605156,  1.03886385, -1.08028232,  0.04424024]])

In [34]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

# array indekslenmesi

In [35]:
arr  = np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [51]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [54]:
np.array(arr[arr > 40]).reshape(6,10)

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [60]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [72]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [80]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [82]:
arr[:3,1]

array([ 2, 12, 22])

In [84]:
arr[:3,1:2]

array([[ 2],
       [12],
       [22]])

In [85]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# array operasyonları

In [88]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [89]:
arr1

array([[1, 3, 4],
       [3, 3, 3],
       [0, 1, 0]])

In [90]:
arr2

array([[3, 4, 3],
       [2, 1, 3],
       [1, 0, 2]])

In [91]:
arr1 + arr2

array([[4, 7, 7],
       [5, 4, 6],
       [1, 1, 2]])

In [92]:
arr1 * arr2

array([[ 3, 12, 12],
       [ 6,  3,  9],
       [ 0,  0,  0]])

In [93]:
arr1.mean()

2.0

In [94]:
arr1.sum()

18