# numpy array yapısı

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]
arr2 = np.array(data_list2)
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
arr3 = np.array([1,2,3,4,5,6])
arr3
arr3[2]

3

In [9]:
arr2[2,2]

90

In [10]:
arr2[5,5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [18]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.randint(0,10)

2

In [39]:
np.random.randint(15)

11

In [41]:
np.random.randint(1,20,5)

array([17, 11,  9,  4,  1])

In [42]:
np.random.rand(5)

array([0.88250731, 0.2982676 , 0.31793108, 0.45312185, 0.31279208])

In [43]:
np.random.randn(5)

array([-0.21277388,  1.46559117, -1.43949786, -0.53770814, -0.17968856])

In [44]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [48]:
newArr = np.random.randint(1,100,10)
newArr

array([91, 22, 32, 11, 23, 68,  4,  1, 82, 90])

In [49]:
newArr.max()

91

In [50]:
newArr.min()

1

In [51]:
newArr.sum()

424

In [52]:
newArr.mean()

42.4

In [53]:
newArr.argmax()

0

In [54]:
newArr.argmin()

7

In [57]:
detArray =np.random.randint(1,100,25)
detArray

array([18, 71, 73, 55, 27, 70, 29, 70, 82, 34, 39, 88, 33, 53, 42, 89, 63,
       24, 94, 92, 23,  8, 29, 47,  9])

In [58]:
detArray = detArray.reshape(5,5)

In [59]:
detArray

array([[18, 71, 73, 55, 27],
       [70, 29, 70, 82, 34],
       [39, 88, 33, 53, 42],
       [89, 63, 24, 94, 92],
       [23,  8, 29, 47,  9]])

In [60]:
np.linalg.det(detArray)

-210002089.9999994

In [62]:
detArray2 = np.array([[1,2],[3,4]])
np.linalg.det(detArray2)

-2.0000000000000004

In [63]:
round(np.linalg.det(detArray2))

-2

# numpy - arraylerin indekslenmesi

In [75]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr[2]

3

In [77]:
arr[1:5]

array([2, 3, 4, 5])

In [78]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
arr[-1]

9

In [80]:
arr[::3]

array([1, 4, 7])

In [81]:
arr[:3]

array([1, 2, 3])

In [82]:
arr[:3] = 25

In [83]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [84]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr2 = arr

In [86]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr2[:3] = 100

In [88]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [89]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [90]:
arr = np.arange(1,10)

In [95]:
arr2 = arr.copy()
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr2[:3] = 25

In [98]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [99]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
newArray = np.arange(1,21)
newArr

array([91, 22, 32, 11, 23, 68,  4,  1, 82, 90])

In [102]:
newArray.reshape(5,4)
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [104]:
newArray = newArray.reshape(5,4)
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [105]:
newArray[0,0]

1

In [106]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [107]:
newArray[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [108]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [112]:
booleanArray = arr > 3

In [113]:
arr[booleanArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [114]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# numpy array operasyonları ve fonksiyonlar

In [116]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,3,4,5,6,7])

In [117]:
arr1 + arr2

array([12, 23, 34, 45, 56, 67])

In [119]:
arr1 - arr2

array([ 8, 17, 26, 35, 44, 53])

In [120]:
arr1 * arr2

array([ 20,  60, 120, 200, 300, 420])

In [121]:
arr1 + 10 

array([20, 30, 40, 50, 60, 70])

In [122]:
arr2 

array([2, 3, 4, 5, 6, 7])

In [123]:
arr2 -2 

array([0, 1, 2, 3, 4, 5])

In [124]:
arr1 / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

In [125]:
arr1

array([10, 20, 30, 40, 50, 60])

In [126]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

# bitiş